services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm --workspace=@apps/backend run dev
    working_dir: /work
    environment:
      NODE_ENV: development
      PORT: 4000
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      LOG_LEVEL: debug
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  owner-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm --workspace=@apps/owner-web run dev-docker
    working_dir: /work
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: http://localhost:4000
    depends_on:
      - backend

  borrower-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm --workspace=@apps/borrower-web run dev-docker
    working_dir: /work
    ports:
      - "5174:5174"
    environment:
      VITE_BACKEND_URL: http://localhost:4000
    depends_on:
      - backend

  admin-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm --workspace=@apps/admin-web run dev-docker
    working_dir: /work
    ports:
      - "5175:5175"
    environment:
      VITE_BACKEND_URL: http://localhost:4000
    depends_on:
      - backend

volumes:
  pgdata:
